---
- name: Verify Minimum Software Version
  assert:
    that: "{{ansible_lsb.release is version_compare('3.7.11', '>=') }}"
    msg: >
      "Cumulus Linux version must be 3.7.11 or later.
      Version {{ansible_lsb.release}} detected"

- name: Copy FRR daemons file
  copy:
    src: daemons
    dest: /etc/frr/daemons
    backup: yes

- name: Copy interfaces configuration
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    backup: yes

- name: Copy FRR configuration
  template:
    src: frr.j2
    dest: /etc/frr/frr.conf
    backup: yes

- name: Reboot Devices
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 45
    test_command: whoami
