---
- name: Verify Minimum Software Version
  assert:
    that: "{{ansible_lsb.release is version_compare('3.7.11', '>=') }}"
    msg: >
      "Cumulus Linux version must be 3.7.11 or later.
      Version {{ansible_lsb.release}} detected"

- name: Initial Switch Management VRF setup
  nclu:
    commit: true
    description: "Initial Management VRF setup"
    commands:
      - add vrf mgmt
      - add hostname "{{ ansible_hostname }}"

- name: Reboot Devices
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 45
    test_command: whoami
