---

- name: Install NetQ Agent
  apt:
    pkg: netq-agent
    state: present
    update_cache: yes

- name: Restart AIR agent (configures NetQ Agent)
  systemd:
    name: air-agent
    state: restarted

- name: Flush Handlers, best practice
  meta: flush_handlers
