---
- name: Verify Minimum Software Version
  assert:
    that: "{{ansible_lsb.release is version_compare('3.7.11', '>=') }}"
    msg: >
      "Cumulus Linux version must be 3.7.11 or later.
      Version {{ansible_lsb.release}} detected"

#- name: Initial Switch Management VRF setup
#  nclu:
#    commit: true
#    description: "Initial Management VRF setup"
#    commands:
#      - add vrf mgmt
#      - add hostname "{{ ansible_hostname }}"
#  notify: reload networking

- name: Copy FRR daemons file
  copy:
    src: daemons
    dest: /etc/frr/daemons
    backup: yes
  notify: restart frr

- name: Copy interfaces configuration
  copy:
    src: configurations/{{ansible_hostname}}_interfaces.txt
    dest: /etc/network/interfaces
    backup: yes
  notify: reload networking

- name: Copy FRR configuration
  copy:
    src: configurations/{{ansible_hostname}}_frr.txt
    dest: /etc/frr/frr.conf
    backup: yes
  notify: reload frr

- name: Flush Handlers, best practice
  meta: flush_handlers
